
package database;
import static bookstore.Bookstore.getConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
/*@author Carolina Colunga*/
public class libro extends javax.swing.JFrame {
     static String fecha() {
        String timeStamp = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());
        System.out.println(timeStamp);
        return timeStamp.toString();
    }
    /**
     * Creates new form libro
     */
    public libro() {
        initComponents();
        cargarTabla();
        this.setLocationRelativeTo(null);
        PreparedStatement ps = null, ps2 = null, ps3;
        ResultSet rs = null, rs2= null, rs3;
        Connection conn = getConnection();
        
        try{
           //String usuario = (String) box_usuario.getSelectedItem();
           //String pass = txt_pass.getText();
           
            String sql = "SELECT distinct seccion FROM registro";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            
            String sql2 = "SELECT distinct encuadernacion FROM libro";
            ps2 = conn.prepareStatement(sql2);
            rs2 = ps2.executeQuery();
            
            /*String sql3 = "SELECT usuario FROM empleado";
            ps3 = conn.prepareStatement(sql3);
            rs3 = ps3.executeQuery();*/
            
            box_sec.addItem("");
            box_enc.addItem("");
            while(rs.next()){
                box_sec.addItem(rs.getString("seccion"));
            }
            while(rs2.next()){
                box_enc.addItem(rs2.getString("encuadernacion"));
            }
            /*while(rs3.next()){
                box_usuario.addItem(rs3.getString("usuario"));
            }*/
            
            rs.close();
            rs2.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_libros = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_isbn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_edicion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_editorial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_idioma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_pag = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();
        box_sec = new javax.swing.JComboBox<>();
        box_enc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libro");

        tbl_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Nombre", "Paginas", "Editorial", "Año de edicion", "Idioma", "Encuadernacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_librosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_libros);
        if (tbl_libros.getColumnModel().getColumnCount() > 0) {
            tbl_libros.getColumnModel().getColumn(0).setResizable(false);
            tbl_libros.getColumnModel().getColumn(1).setResizable(false);
            tbl_libros.getColumnModel().getColumn(2).setResizable(false);
            tbl_libros.getColumnModel().getColumn(3).setResizable(false);
            tbl_libros.getColumnModel().getColumn(4).setResizable(false);
            tbl_libros.getColumnModel().getColumn(5).setResizable(false);
            tbl_libros.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel10.setText("ISBN");

        txt_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isbnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel3.setText("Año de edicion");

        txt_edicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edicionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel4.setText("Editorial");

        txt_editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_editorialActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel5.setText("Idioma");

        txt_idioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idiomaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel6.setText("Encuadernacion");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel8.setText("Nombre");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Actualizar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel2.setText("Paginas");

        txt_pag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pagActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Seccion");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Usuario");

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        box_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_secActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txt_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21)
                        .addComponent(box_enc, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(box_sec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modificar)
                        .addGap(328, 328, 328)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limpiar)
                        .addGap(57, 57, 57)
                        .addComponent(btn_salir)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(box_sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_enc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_limpiar)
                    .addComponent(btn_salir)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31))
        );

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setText("Libros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_librosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_librosMouseClicked
        // TODO add your handling code here:
        try{
            int fila = tbl_libros.getSelectedRow();
            String isbn = tbl_libros.getValueAt(fila, 0).toString();
            PreparedStatement ps;
            ResultSet rs;
            
            Connection conn = getConnection();
            ps = conn.prepareStatement("SELECT nombre, paginas, editorial, edicion, idioma, encuadernacion FROM libro WHERE ISBN=?");
            ps.setString(1, isbn);
            rs = ps.executeQuery();
            while(rs.next()){
                txt_isbn.setText(String.valueOf(isbn));
                txt_nombre.setText(rs.getString("nombre"));
                txt_pag.setText(rs.getString("paginas"));
                txt_editorial.setText(rs.getString("editorial"));
                txt_edicion.setText(rs.getString("edicion"));
                txt_idioma.setText(rs.getString("idioma"));
                box_enc.setSelectedItem(rs.getString("encuadernacion")); 
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_tbl_librosMouseClicked

    private void txt_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnActionPerformed

    private void txt_pagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pagActionPerformed

    private void txt_edicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edicionActionPerformed

    private void txt_editorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_editorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_editorialActionPerformed

    private void txt_idiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idiomaActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        String isbn = txt_isbn.getText();
        String nombre = txt_nombre.getText();
        int pag = Integer.parseInt(txt_pag.getText());
        String editorial = txt_editorial.getText();
        int edicion = Integer.parseInt(txt_edicion.getText());
        String idioma = txt_idioma.getText();
        String enc = (String) box_enc.getSelectedItem();
        
        String libro_isbn = txt_isbn.getText();
        String seccion = (String) box_sec.getSelectedItem();
        String mov = "Registro";
        String fecha = fecha();
        int usuario = Integer.parseInt(txt_usuario.getText());
        
        try{
            Connection conn = getConnection();
            if (0 == verificar()){
                limpiar();
            }else{
                PreparedStatement ps = conn.prepareStatement("INSERT INTO libro (ISBN, nombre, paginas, editorial, edicion, idioma, encuadernacion) VALUES (?,?,?,?,?,?,?)");
                PreparedStatement ps2 = conn.prepareStatement("INSERT INTO registro (seccion, usuario_emp, libro_ISBN, movimiento, fecha) VALUES (?,?,?,?,?)");

                ps.setString(1, isbn);
                ps.setString(2, nombre);
                ps.setInt(3, pag);
                ps.setString(4, editorial);
                ps.setInt(5, edicion);
                ps.setString(6, idioma);
                ps.setString(7, enc);
                ps.executeUpdate();
                
                ps2.setString(1, seccion);
                ps2.setInt(2, usuario);
                ps2.setString(3, libro_isbn);
                ps2.setString(4, mov);
                ps2.setString(5, fecha);
                ps2.executeUpdate();

                JOptionPane.showMessageDialog(null,"Registro guardado");
                limpiar();
                cargarTabla();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        String isbn = txt_isbn.getText();
        String nombre = txt_nombre.getText();
        int pag = Integer.parseInt(txt_pag.getText());
        String editorial = txt_editorial.getText();
        int edicion = Integer.parseInt(txt_edicion.getText());
        String idioma = txt_idioma.getText();
        String enc = (String) box_enc.getSelectedItem();
        
        String libro_isbn = txt_isbn.getText();
        String seccion = (String) box_sec.getSelectedItem();
        String mov = "Modificacion";
        String fecha = fecha();
        int usuario = Integer.parseInt(txt_usuario.getText());
        
        //txt_isbn.setEditable(false);
        
        try{
            Connection conn = getConnection();
            if (0 == verificar()){
                limpiar();
            }else{
                PreparedStatement ps = conn.prepareStatement("UPDATE libro SET nombre=?, paginas=?, editorial=?, edicion=?, idioma=?, encuadernacion=? WHERE ISBN=?");
                PreparedStatement ps2 = conn.prepareStatement("INSERT INTO registro (seccion, usuario_emp, libro_ISBN, movimiento, fecha) VALUES (?,?,?,?,?)");

                ps.setString(1, nombre);
                ps.setInt(2, pag);
                ps.setString(3, editorial);
                ps.setInt(4, edicion);
                ps.setString(5, idioma);
                ps.setString(6, enc);
                ps.setString(7, isbn);
                ps.executeUpdate();

                ps2.setString(1, seccion);
                ps2.setInt(2, usuario);
                ps2.setString(3, libro_isbn);
                ps2.setString(4, mov);
                ps2.setString(5, fecha);
                ps2.executeUpdate();

                JOptionPane.showMessageDialog(null,"Registro actualizado");
                limpiar();
                cargarTabla();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        Connection conn = getConnection();
        String isbn = txt_isbn.getText();
        try{
            if (0 == verificar()){
                limpiar();
            }else{
                PreparedStatement ps = conn.prepareStatement("DELETE FROM libro WHERE isbn=?");
                ps.setString(1, isbn);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null,"Registro eliminado");
                limpiar();
                cargarTabla();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        limpiar2();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
         sistema ventana = new sistema();
        ventana.setVisible(true);
        this.hide(); // Se cierre la ventana
    }//GEN-LAST:event_btn_salirActionPerformed

    private void box_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_secActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_box_secActionPerformed
    /*private void insertar(){
        Connection conn = getConnection();
        String libro_isbn = txt_isbn.getText();
        String seccion = txt_sec.getText();
        String mov = "Eliminacion";
        int usuario = Integer.parseInt(txt_usuario.getText());
        
        try{
            PreparedStatement ps2 = conn.prepareStatement("INSERT INTO registro (seccion, usuario_emp, libro_isbn, movimiento) VALUES (?,?,?.?)");
            ps2.setString(1, seccion);
            ps2.setInt(2, usuario);
            ps2.setString(3, libro_isbn);
            ps2.setString(3, mov);
            ps2.executeUpdate(); 
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }*/
    private void limpiar(){
        txt_isbn.setText("");
        txt_nombre.setText("");
        txt_pag.setText("");
        txt_editorial.setText("");
        txt_edicion.setText("");
        txt_idioma.setText("");
    }
    private void limpiar2(){
        txt_usuario.setText("");
    }
    private void cargarTabla(){
       DefaultTableModel  modeloTabla = (DefaultTableModel) tbl_libros.getModel();
       modeloTabla.setRowCount(0);
       
       PreparedStatement ps;
       ResultSet rs;
       ResultSetMetaData rsmd;
       int columnas;
       
       int[]anchos = {10,120,-2,50,2,5,20};
       for(int i = 0; i < tbl_libros.getColumnCount(); i++){
           tbl_libros.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
       }
       
       try{
           Connection conn = getConnection();
           ps = conn.prepareStatement("SELECT ISBN, nombre, paginas, editorial, edicion, idioma, encuadernacion FROM libro");
           rs = ps.executeQuery();
           rsmd = rs.getMetaData();
           columnas = rsmd.getColumnCount();
           
           while(rs.next()){
               Object[]fila = new Object[columnas];
               for(int indice = 0; indice < columnas; indice++){
                   fila[indice] = rs.getObject(indice + 1);
               }
               modeloTabla.addRow(fila);
           }
       }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    private int verificar(){
       int resultado = 0;
       Statement st;
       ResultSet rs;
       
       try{
           String usuario = txt_usuario.getText();
           //String pass = txt_pass.getText();
           Connection conn = getConnection();
           String sql = ("SELECT * FROM empleado WHERE usuario='"+usuario+"'");
           st = conn.createStatement();
           rs = st.executeQuery(sql);
           
           if(rs.next()){
                resultado = 1;
                if(resultado == 1){
                   System.out.println("Se encontro registro");
                   return resultado;
                }  
            }else{
                JOptionPane.showMessageDialog(null,"No existe este usuario en la base de datos");
                return resultado;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
         return 0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new libro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_enc;
    private javax.swing.JComboBox<String> box_sec;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_libros;
    private javax.swing.JTextField txt_edicion;
    private javax.swing.JTextField txt_editorial;
    private javax.swing.JTextField txt_idioma;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_pag;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
