
package database;
/*@author Carolina Colunga*/

public class sistema extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        empleado = new javax.swing.JMenu();
        registrarEmp = new javax.swing.JMenuItem();
        modificarEmp = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ingresarLibros = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        verRegistros = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libreria.png"))); // NOI18N

        jMenuBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.lightGray)));

        empleado.setText("Empleado");

        registrarEmp.setText("Registrar");
        registrarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpActionPerformed(evt);
            }
        });
        empleado.add(registrarEmp);

        modificarEmp.setText("Modificar");
        modificarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEmpActionPerformed(evt);
            }
        });
        empleado.add(modificarEmp);

        jMenuBar1.add(empleado);

        jMenu2.setText("Libros");

        ingresarLibros.setText("Ingresar");
        ingresarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarLibrosActionPerformed(evt);
            }
        });
        jMenu2.add(ingresarLibros);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Registros");

        verRegistros.setText("Ver");
        verRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRegistrosActionPerformed(evt);
            }
        });
        jMenu4.add(verRegistros);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Sistema");

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu3.add(salir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarLibrosActionPerformed
        // TODO add your handling code here:
        libro form = new libro();
        form.setVisible(true);
        this.hide();
    }//GEN-LAST:event_ingresarLibrosActionPerformed

    private void registrarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpActionPerformed
        // TODO add your handling code here:
        empleado form = new empleado();
        form.setVisible(true);
        this.hide();
    }//GEN-LAST:event_registrarEmpActionPerformed

    private void modificarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEmpActionPerformed
        // TODO add your handling code here:
        validacion form = new validacion();
        form.setVisible(true);
        this.hide();
    }//GEN-LAST:event_modificarEmpActionPerformed

    private void verRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRegistrosActionPerformed
        // TODO add your handling code here:
        registro form = new registro();
        form.setVisible(true);
        this.hide();
    }//GEN-LAST:event_verRegistrosActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu empleado;
    private javax.swing.JMenuItem ingresarLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem modificarEmp;
    private javax.swing.JMenuItem registrarEmp;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem verRegistros;
    // End of variables declaration//GEN-END:variables
}
